apiVersion: apps/v1
kind: Deployment
metadata:
  name: wwdicebot
  namespace: bots
spec:
  replicas: {{ .Values.replicas | default 3 }}
  selector:
    matchLabels:
      app: wwdicebot
  template:
    metadata:
      labels:
        app: wwdicebot
    spec:
      containers:
        - name: wwdicebot
          resources:
            limits:
              cpu: {{ .Values.cpu_limit }}
              memory: {{ .Values.memory_limit | quote }}
            requests:
              cpu: {{ .Values.cpu_request }}
              memory: {{ .Values.memory_request | quote }}
          image: 'docker.io/klaital/wwdicebot:latest'
          imagePullPolicy: Always
          ports:
            - name: http-profile
              containerPort: 8080
          env:
            - name: DISCORD_BOT_TOKEN
              valueFrom:
                secretKeyRef:
                  name: discord-secret
                  key: bot-token
          readinessProbe:
            httpGet:
              path: /healthz?readiness
              port: 8080
            periodSeconds: 20
            timeoutSeconds: 30
            successThreshold: 1
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: /healthz?liveness
              port: 8080
            initialDelaySeconds: 45
            periodSeconds: 60
---
apiVersion: v1
kind: Service
metadata:
  name: wwdicebot
  namespace: bots
spec:
  type: NodePort
  selector:
    app: mango-profile-service
  ports:
    - name: http-mango-prof
      port: 80
      targetPort: 8080
      protocol: TCP
---
apiVersion: v1
kind: Namespace
metadata:
  name: bots